<?php

return [
    [
        'group' => '基本信息',
        'name' => 'defaultConfInfoLables',
        'title' => '默认的活动栏目，多个逗号分隔',
        'type' => 'string',
        'content' => [],
        'value' => '简介,议程,交通,联系人',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'group' => '基本信息',
        'name' => 'xcbaseurl',
        'title' => '网站域名',
        'type' => 'string',
        'content' => [],
        'value' => 'http://www.example.com/',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'group' => '登录配置',
        'name' => 'cloginwxmp',
        'title' => '<b>小程序登录</b>',
        'type' => 'radio',
        'content' => [
            'Y' => '启用',
            'N' => '不启用',
        ],
        'value' => 'N',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'group' => '登录配置',
        'visible' => 'cloginwxmp=Y',
        'name' => 'cloginwxmpappid',
        'title' => '&nbsp;&nbsp;&nbsp;appid',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '微信小程序appid',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'group' => '登录配置',
        'visible' => 'cloginwxmp=Y',
        'name' => 'cloginwxmpappsecret',
        'title' => '&nbsp;&nbsp;&nbsp;appsecret',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '微信小程序appsecret',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'group' => '登录配置',
        'name' => 'cloginwxoa',
        'title' => '<b>公众号登录</b>',
        'type' => 'radio',
        'content' => [
            'Y' => '启用',
            'N' => '不启用',
        ],
        'value' => 'N',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'group' => '登录配置',
        'visible' => 'cloginwxoa=Y',
        'name' => 'cloginwxoaappid',
        'title' => '&nbsp;&nbsp;&nbsp;appid',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '微信公众号appid',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'group' => '登录配置',
        'visible' => 'cloginwxoa=Y',
        'name' => 'cloginwxoaappsecret',
        'title' => '&nbsp;&nbsp;&nbsp;appsecret',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '微信公众号appsecret',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'group' => '隐私服务',
        'name' => 'cloginprivatepolicy',
        'title' => '<b>用户隐私协议</b>',
        'type' => 'text',
        'content' => [],
        'value' => '用户隐私协议'."\r\n"
            .'用户隐私协议',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'group' => '隐私服务',
        'name' => 'cloginservicepolicy',
        'title' => '<b>用户服务协议</b>',
        'type' => 'text',
        'content' => [],
        'value' => '用户服务协议'."\r\n"
            .'用户服务协议',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'group' => '隐私服务',
        'name' => 'clogincontactme',
        'title' => '<b>联系我</b>',
        'type' => 'text',
        'content' => [],
        'value' => '如果您对本服务有任何意见或建议，或您对本服务条款内容有任何疑问，可发邮件至chenshiming0802@163.com。',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'group' => '隐私服务',
        'name' => 'cloginwenjuanurl',
        'title' => '<b>意见反馈</b>',
        'type' => 'text',
        'content' => [],
        'value' => 'https://www.wjx.cn/vm/hv0Ye0f.aspx#',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
